### ISSUE TITLE
Dependencies update

### ISSUE THREAD

**Issue by Arpic** [elastic/thumbnails4j#29]
Hi,

We're trying to use this library in one of our project but we're running into conflicts because we're using a more recent version of poi-ooxml. Would it be possible to publish a version of this library with more up-to-date dependencies?
I can make a PR assuming units tests are sufficient.

Thanks for your consideration and the nice library!

**Comment by seanstory** [comment]
@Arpic have you tried including thumbnails4j with the maven shade plugin, or just managing the dependency up?

**Comment by Arpic** [comment]
We're using gradle so the shade plugin is not an option. I can exclude the transitive dependencies, but the interface for
`org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPageSz` has changed which makes `DocxThumbnailer` incompatible with later versions of poi-ooxml.

**Comment by Arpic** [comment]
Indeed I realize you cannot match everyone's dependencies, and we will figure out a solution for our situation. 
I guess it's still worth keep your dependencies up-to-date where possible.
Thanks for your answer 👍
